from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import settings

# Importing `app.db.base` is what populates `Base.metadata`. Every model
# module must be imported there, or autogenerate will not see its table.
from app.db.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# What autogenerate compares the live database against.
target_metadata = Base.metadata


def get_url() -> str:
    """The database URL, from the environment rather than alembic.ini.

    Keeping it out of the ini file means the connection string exists only in
    `.env`, which is git-ignored — it cannot be committed by accident.
    """
    return settings.require_database_url()


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting.

    `alembic upgrade head --sql` produces a script for review or for a DBA to
    apply by hand.
    """
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect and apply migrations."""
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = get_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # Without these, a changed column type or server default is
            # silently omitted from an autogenerated migration.
            compare_type=True,
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
